# Generated by Django 4.2.3 on 2023-07-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_time", models.TimeField()),
                (
                    "semester",
                    models.CharField(
                        choices=[("odd", "Odd"), ("even", "Even")],
                        default="Odd",
                        max_length=10,
                    ),
                ),
                (
                    "types",
                    models.CharField(
                        choices=[("regular", "Regular"), ("back", "Back")],
                        default="Regular",
                        max_length=10,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[("morning", "Morning"), ("day", "Day")],
                        default="Morning",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invigilator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("email", models.CharField(max_length=50, unique=True)),
                ("phone", models.CharField(max_length=50, unique=True)),
                ("address", models.CharField(max_length=70, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="Male",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.IntegerField()),
                (
                    "building",
                    models.ForeignKey(
                        default="ICTC",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IMSapp.building",
                    ),
                ),
            ],
            options={"unique_together": {("building", "room_number")},},
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                (
                    "shift",
                    models.CharField(
                        choices=[("morning", "Morning"), ("day", "Day")],
                        default="Morning",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="IMSapp.exam"
                    ),
                ),
                (
                    "invigilators",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IMSapp.invigilator",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IMSapp.room",
                    ),
                ),
            ],
            options={"unique_together": {("shift", "room", "date", "invigilators")},},
        ),
    ]
