# Generated by Django 4.2.3 on 2023-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IMSapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invigilator",
            name="post",
            field=models.CharField(default="Teacher", max_length=50, unique=True),
        ),
    ]
