# Generated by Django 4.2.3 on 2023-07-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IMSapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="exam", name="start_time",),
        migrations.AlterUniqueTogether(
            name="examsession", unique_together={("shift", "date", "invigilators")},
        ),
        migrations.RemoveField(model_name="examsession", name="start_time",),
    ]
