# Generated by Django 4.2.3 on 2023-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IMSapp", "0002_remove_exam_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="shift",
            field=models.CharField(
                choices=[
                    ("morning", "Morning"),
                    ("day", "Day"),
                    ("evening", "Evening"),
                ],
                default="Morning",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="shift",
            field=models.CharField(
                choices=[
                    ("morning", "Morning"),
                    ("day", "Day"),
                    ("evening", "Evening"),
                ],
                default="Morning",
                max_length=10,
            ),
        ),
    ]
