# Generated by Django 4.2.3 on 2023-08-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IMSapp", "0002_alter_invigilator_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invigilator",
            name="address",
            field=models.CharField(default="Lalitpur", max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="invigilator",
            name="age",
            field=models.IntegerField(default="20", null=True),
        ),
        migrations.AlterField(
            model_name="invigilator",
            name="email",
            field=models.CharField(
                default="test@test.com", max_length=50, null=True, unique=True
            ),
        ),
    ]
