# Generated by Django 4.2.3 on 2023-07-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IMSapp", "0003_alter_exam_shift_alter_examsession_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invigilator", name="age", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="invigilator",
            name="email",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="invigilator",
            name="phone",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
