# Generated by Django 4.2.3 on 2023-08-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IMSapp", "0004_alter_invigilator_address_alter_invigilator_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invigilator",
            name="address",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="invigilator",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invigilator",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
