# Generated by Django 4.2.3 on 2023-08-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IMSapp", "0005_alter_invigilator_address_alter_invigilator_age_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invigilator", unique_together={("post", "firstname")},
        ),
    ]
