# Generated by Django 4.2.3 on 2023-08-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IMSapp", "0006_alter_invigilator_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invigilator",
            name="post",
            field=models.CharField(max_length=50),
        ),
    ]
