# Generated by Django 4.2.3 on 2023-08-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IMSapp", "0007_alter_invigilator_post"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invigilator", unique_together={("post", "firstname", "lastname")},
        ),
    ]
